apiVersion: hspc.hitachi.com/v1alpha2
kind: DRPolicy
metadata:
  name: drpolicy-protectedns-async
  namespace: hspc-replication-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  pvcSelector:
    matchNamespaces:
      - protected-ns
  drTarget:
    clusterName: dc2-emea-coe
  replicationMode: async
  consistencyRequired: true
  consistencyGroupName: spc-ur-png-03
  primaryJournalId: 3
  secondaryJournalId: 3
  #readyOrderOfPvcByNamespace:
  #  - demo-ur-db
  #  - demo-ur-app
  # readyOrderOfPvcByLabel:
  #   - app: apps-1
  # replicationAttribute: primary
  #actionsAfterStorageFailover:
  actionsOnTarget:
    - scriptType: shell
      configMapRef:
        name: post-failover-script
        key: run.sh
