apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    argocd.argoproj.io/sync-wave: "2"
  name: dro-vm-pns-02
  namespace: protected-ns
spec:
  runStrategy: Manual
  template:
    spec:
      architecture: amd64
      domain:
        devices:
          autoattachPodInterface: false
          interfaces:
            - macAddress: '02:be:30:00:00:09'
              masquerade: {}
              name: default
        machine:
          type: pc-q35-rhel9.4.0
        resources:
          requests:
            memory: 6Gi
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: dro-vm-pns-02-volume
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: hitachi
              user: fedora
          name: cloudinitdisk
