apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dro-vm-pns-02
  namespace: protected-ns
  labels:
    app: dro-vm-pns-02
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    argocd.argoproj.io/sync-wave: "2"
spec:
  runStrategy: Manual
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: dro-vm-pns-02-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          storageClassName: sc-gold-replicated
          resources:
            requests:
              storage: 30Gi
  template:
    metadata:
      labels:
        kubevirt.io/domain: dro-vm-pns-02
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        memory:
          guest: 8Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: dro-vm-pns-02-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
              # Set a password or use SSH keys below (recommended)
              password: hitachi
              # Uncomment to inject your SSH public key
              # ssh_authorized_keys:
              #   - ssh-ed25519 AAAA... yourkey
